### ISSUE TITLE
[request] strong naming signed

### ISSUE THREAD

**Issue by SquallATF** [Panuon/Panuon.WPF.UI#125]
If strong naming is enabled, the project could not be referenced.

**Comment by Mochengvia** [comment]
As I don't have an official company CA certificate yet, I can't sign this project for now.
You can download the project and compile it signed with your own certificate.

**Comment by Mochengvia** [comment]
As I said, strong names must sign the assembly with a code signing certificate.
Our company has not purchased a code signing certificate, and we cannot sloppily sign the assembly with the pfx certificate we created, which will cause many problems.
This issue will remain open, but will not be resolved immediately.

**Comment by SquallATF** [comment]
strong name not need code signing certificate
snk can be generated from Visual Studio Developer Command Prompt
```
sn -k somename.snk
```
or with keysize
```
sn -k 4096 somename.snk
```
Then add the following to each csproj 
```xml
  <PropertyGroup>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>somename.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
```
or create a `Directory.Build.props` for all project
```xml
<Project>
  <PropertyGroup>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>somename.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
</Project>
```

**Comment by Mochengvia** [comment]
You don't seem to get what I mean.
For assemblies signed with a certificate, the signer's information will be displayed on the file property page. What I mean is, if we want to enable the signing certificate to strongly sign the assembly, we must use the certificate with our company name to sign it instead of using the certificate file generated by ourselves (such as the sn command you said ).

**Comment by Mochengvia** [comment]
From `1.1.14` , `Panuon.WPF.UI` has enabled strong signing with the company's code signing certificate.
